language: java

env:
  global:
    secure: GfoA8QZ2NaN61FEePvUWzM+Rq8TV5Rk3hcUBYDmjXPU5IqO/ytx5DMtpiS0fIZSrq9+efrCqPOP5cAlMxrvM+Q/I9fknUTsetjV9jEbgoAVV9F/97h5VnWk67dfHPz7bVUvbF+mrnczrPCJUDd2/T7E1LuVBHZHJ3FHTk3W+TaE=

branches:
  except:
    - /^release-.*$/

jdk:
  - oraclejdk8

install: ./build ci-prepare -V -B -s .travis/settings.xml

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "true" -o "$TRAVIS_BRANCH" != "master" ] ; then ./build ci-verify -V -B -s .travis/settings.xml ; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ] ; then ./build ci-deploy -V -B -s .travis/settings.xml ; fi'
